= Boost.Signals2

Amonst various signals/slots libraries (https://github.com/NoAvailableAlias/nano-signal-slot/tree/master/benchmark#performance[examples]), Boost Signals2 is very good choice, regarding *safety* and *flexibility*. (There is a tradeoff with speed: you cannot get everything).

The destructor of a signal, will result in the destructor of the associated functor-slots. A lurking danger might be: what if the slot-code (functor) destructs the signal that actually resulted in the slot-call --- the danger being: this could self-destruct the functor-slot whose code is just running!!! It seems, that this is no problem for Signals2...

The example shows a signal and then 5 slots (functors) being connected to that signal. When the signal is emitted, the 3rd triggered slot actually calls the signal's destructor (provided that `DELETE_SIG_IN_FUNCTOR_SLOT` is defined)! This destruction of the signal, does _not_ cause havoc by simultaneously destructing the slot (that would be like self-destruction during execution!), rather the slot continues; and even all further slots are nicely executed. Only after all slots have been called, will the destructors of the slots (functors) be called. Now that's safe code!!!

If `DELETE_SIG_IN_FUNCTOR_SLOT` is undefined, then the signal's destructor will only be called, if no more `shared_ptr` instance remains. But here there is an interesting constellation: the signal holds copies of the functors (which each hold ``shared_ptr``s of the signal itself). 

Therefore the scope-end of `sig_p` is not enough to call destructors, since there are still functors holding ``shared_ptr``s (to the signal). Thus to call the destructors, we must explicitly call the signal's destructor (https://github.com/ajneu/cpp_experiments/blob/master/signals2/main.cpp#L164[ref] - causing the `unique_ptr` to hold `nullptr` and destruct the signal) which in turn destructs the held functors, removing all ``shared_ptr``s until none remain, causing the `shared_ptr` to delete the `unique_ptr` (which was already holding `nullptr` and can be "trivially" deleted).
